language: perl6

perl6:
    - latest

install:
    - rakudobrew build-panda
    - panda update && panda install LWP::Simple

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgtk-3-dev
