language: minimal

os:
  - linux
  - osx

before_install:
  - echo $TRAVIS_OS_NAME
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update           ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install libgtk-3-dev ; fi
  # macOS
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                       ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install gtk+3                ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then ulimit -n 8192                    ; fi

services:
  - docker

install:
  - docker pull jjmerelo/raku-test

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test
