os: Visual Studio 2017

platform: x64

install:
    vcpkg install gtk:x64-windows

shallow_clone: true

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
